export const aiServicesData = [
  {
    id: 1,
    image: '',
    rating: 5,
    title: 'Natural Language Processing',
    description: 'Advanced language processing for chatbots and text analysis.',
  },
  {
    id: 2,
    image: 'service2.jpg',
    name: '',
    rating: 3,
    title: 'Image Recognition',
    description: 'Identify objects, faces, and scenes in images and videos.',
  },
  {
    id: 3,
    image: 'service3.jpg',
    rating: 5,
    title: 'Machine Learning Algorithms',
    description: 'Custom machine learning models for predictive analytics.',
  },
  {
    id: 4,
    image: 'service4.jpg',
    rating: 4,
    title: 'Speech Recognition',
    description: 'Convert spoken language into written text for transcription.',
  },
  {
    id: 5,
    image: 'service5.jpg',
    rating: 4,
    title: 'Recommendation Systems',
    description: 'Personalized product and content recommendations.',
  },
  {
    id: 6,
    image: 'service6.jpg',
    rating: 4,
    title: 'Computer Vision',
    description: 'Extract information from images for various applications.',
  },
  {
    id: 7,
    image: 'service7.jpg',
    rating: 4,
    title: 'Natural Language Generation',
    description: 'Generate human-like text content for chatbots and reports.',
  },
  {
    id: 8,
    image: 'service8.jpg',
    rating: 4,
    title: 'Predictive Analytics',
    description: 'Utilize historical data to make predictions and inform decisions.',
  },
  {
    id: 9,
    image: 'service9.jpg',
    rating: 4,
    title: 'Data Visualization',
    description: 'Create interactive charts and graphs to explore data.',
  },
  {
    id: 10,
    image: 'service10.jpg',
    rating: 4,
    title: 'Voice Assistants',
    description: 'Build voice-enabled applications and virtual assistants.',
  },

  {
    id: 11,
    image: 'service11.jpg',
    rating: 5,
    title: 'Robotics',
    description: 'Design, build, and program intelligent robots and drones.',
  },
  {
    id: 12,
    image: 'service12.jpg',
    rating: 4,
    title: 'Internet of Things',
    description: 'Connect and manage networks of physical devices and sensors.',
  },
  {
    id: 13,
    image: 'service13.jpg',
    rating: 5,
    title: 'Customer Segmentation',
    description: 'Divide customers into groups based on common attributes.',
  },
  {
    id: 14,
    image: 'service14.jpg',
    rating: 4,
    title: 'Chatbots',
    description: 'Create conversational interfaces powered by NLP and dialog management.',
  },
  // ...
  {
    id: 21,
    image: 'service21.jpg',
    rating: 5,
    title: 'Virtual Agents',
    description: 'Provide automated customer service through avatars.',
  },
  {
    id: 22,
    image: 'service22.jpg',
    rating: 4,
    title: 'Network Analysis',
    description: 'Analyze the relationships in complex networks and graphs.',
  },
  {
    id: 23,
    image: 'service23.jpg',
    rating: 5,
    title: 'Neural Networks',
    description: 'Build and train neural net models for complex data.',
  },
  {
    id: 24,
    image: 'service24.jpg',
    rating: 4,
    title: 'Reinforcement Learning',
    description: 'Develop agents that learn by interacting with environments.',
  },
  {
    id: 25,
    image: 'service25.jpg',
    rating: 3,
    title: 'Automated Planning',
    description: 'Create systems that can formulate plans and make decisions.',
  },
  {
    id: 26,
    image: 'service26.jpg',
    rating: 5,
    title: 'Computer Audition',
    description: 'Extract information from audio signals.',
  },
  {
    id: 27,
    image: 'service27.jpg',
    rating: 4,
    title: 'Natural Language Generation',
    description: 'Generate human-like text content.',
  },
  {
    id: 28,
    image: 'service28.jpg',
    rating: 5,
    title: 'Speech Synthesis',
    description: 'Convert text to human-like speech.',
  },
  {
    id: 29,
    image: 'service29.jpg',
    rating: 3,
    title: 'Bioinformatics',
    description: 'Manage and analyze biological data.',
  },
  {
    id: 30,
    image: 'service30.jpg',
    rating: 4,
    title: 'Computer Vision',
    description: 'Extract insights from visual data.',
  },
  {
    id: 31,
    image: 'service31.jpg',
    rating: 5,
    title: 'Expert Systems',
    description: 'Provide decisions based on rules and logic.',
  },
  {
    id: 32,
    image: 'service32.jpg',
    rating: 4,
    title: 'Robot Vision',
    description: 'Enable robots to perceive and interpret visual inputs.',
  },
  {
    id: 33,
    image: 'service33.jpg',
    rating: 3,
    title: 'Cybersecurity',
    description: 'Protect systems and networks from attacks.',
  },
  {
    id: 34,
    image: 'service34.jpg',
    rating: 5,
    title: 'Quantum Computing',
    description: 'Perform complex computations with quantum systems.',
  },
  {
    id: 35,
    image: 'service35.jpg',
    rating: 4,
    title: 'Logistics Optimization',
    description: 'Optimize transportation and logistics operations.',
  },
  {
    id: 36,
    image: 'service36.jpg',
    rating: 4,
    title: 'Anomaly Detection',
    description: 'Identify unusual patterns in data.',
  },
  {
    id: 37,
    image: 'service36.jpg',
    rating: 4,
    title: 'Anomaly Detection',
    description: 'Identify unusual patterns in data.',
  },
  {
    id: 38,
    image: 'service36.jpg',
    rating: 4,
    title: 'Anomaly Detection',
    description: 'Identify unusual patterns in data.',
  },
]

export const sideBarData = [
  {
    id: 1,
    title: 'Artificial Intelligence',
    count: 35,
  },
  {
    id: 2,
    title: 'writing',
    count: 12,
  },
  {
    id: 3,
    title: 'Interactive',
    count: 45,
  },
  {
    id: 4,
    title: 'Q&A format',
    count: 34,
  },
  {
    id: 5,
    title: 'Avatar creation',
    count: 32,
  },
  {
    id: 6,
    title: 'Image editing',
    count: 21,
  },
  {
    id: 7,
    title: 'Email writing',
    count: 32,
  },
  {
    id: 8,
    title: 'Music/drug production',
    count: 18,
  },
  {
    id: 9,
    title: 'Video/video generation',
    count: 32,
  },
  {
    id: 10,
    title: 'prompt',
    count: 50,
  },
  {
    id: 11,
    title: 'Video recognition',
    count: 23,
  },
  {
    id: 12,
    title: 'Tweet generation',
    count: 35,
  },
  {
    id: 13,
    title: 'Customer support',
    count: 27,
  },
  {
    id: 14,
    title: 'Data analysis',
    count: 53,
  },
  {
    id: 15,
    title: 'Meeting',
    count: 53,
  },
  {
    id: 16,
    title: 'Text reading',
    count: 23,
  },
  {
    id: 17,
    title: 'Task automation',
    count: 75,
  },
  {
    id: 9,
    title: 'SEO content creation',
    count: 23,
  },
]
